[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "riskauth_ml"
version = "0.1.0"
description = "Machine learning module for RiskAuth"
authors = [
    {name = "Nehan WIjayagunarathna", email = "nehannimsara0031029@gmail.com"},
]
requires-python = ">=3.8"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "black>=21.0",
    "flake8>=3.9",
]

[tool.setuptools]
packages = ["riskauth_ml"]
